# Generated by Django 3.2.25 on 2024-10-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'v_sales_summary',
                'managed': False,
            },
        ),
    ]
